rand_df <- nutrition[sample(nrow(nutrition), size=100), ]
table(khg388$`Cholesterol Level`)
hist(khg388$Calories, xlab='Calories', main='Calories in Common Foods', right=F, col='orange')
median(khg388$Calories)
IQR(khg388$Calories)
hist(log(khg388$Calories), xlab='Calories', main='Log(Calories) in Common Foods', right=F, col='light blue')
shapiro.test(log(khg388$Calories))
hist(khg388$`Total Fat Content (g)`, xlab='Total Fat Content (g)', main='Total Fat Content in Common Foods', right=F, col='light grey')
median(khg388$`Total Fat Content (g)`)
IQR(khg388$`Total Fat Content (g)`)
hist(log(khg388$`Total Fat Content (g)`), xlab='Total Fat Content (g)', main='Log(Total Fat Content) in Common Foods', right=F, col='red')
plot(khg388$`Total Fat Content (g)`, khg388$Calories, xlab='Total Fat Content (g)', ylab='Calories', main='Total Fat Content and Calories in Common Foods', pch=16)
table(khg388$`Cholesterol Level`)
barplot(table(khg388$`Cholesterol Level`), ylab='Frequency', main='Cholesterol Level in Common Foods', col='dark blue')
boxplot(Calories~CholesterolLevel, data=khg388, xlab='Cholesterol Level', ylab='Calories', main='Cholesterol Level and Calories in Common Foods', col=c('light green','light pink'))
fivenum(khg388$Calories)
fivenum(khg388$`Total Fat Content (g)`)
table(khg388$CholesterolLevel)
khg388$'Total Fat Content (g)'_c <- khg388$'Total Fat Content (g)' - mean(khg388$`Total Fat Content (g)`)

